before_script:
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/14983
  # shared runner 会出现，special runner只会报warning
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

  - pwd
  - ruby -v
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty --no-ri --no-rdoc
  - pod --version
  #- pod cache clean --all
  - git clone git@git.2dfire-inc.com:ios/ci-yaml-shell.git 
  - gem uninstall cocoapods-tdfire-binary --all
  - gem install cocoapods-tdfire-binary
  #- gem install specific_install
  #- gem specific_install -l git@git.2dfire-inc.com:ios/cocoapods-tdfire.git

after_script:
  - rm -fr ci-yaml-shell

stages:
  - lint
  - test
  - package
  - binary_lint
  - publish
  - report
  - cleanup

lib_lint:
  stage: lint
  retry: 2
  script: 
    - ci-yaml-shell/lib_lint_executor.sh
  tags:
    - iOS

oc_lint:
  stage: lint
  script: 
    - ci-yaml-shell/oclint_executor.sh lint_result
  after_script:
    - cat lint_result | python -m json.tool
  tags:
    - iOS

unit_test:
  stage: test
  script: 
    - ci-yaml-shell/unit_test_executor.sh
  tags:
    - iOS

package_framework:
  stage: package 
  only:
    - tags
  script:
    - ci-yaml-shell/framework_pack_executor.sh
  tags:
    - iOS

binary_lint:
  stage: binary_lint
  only:
    - tags
  script:
    - ci-yaml-shell/lib_lint_executor.sh
  tags:
    - iOS

publish_pod:
  stage: publish
  only:
    - tags
  retry: 2
  script:
    - ci-yaml-shell/publish_executor.sh
  tags:
    - iOS
  # allow_failure: true

report_to_director:
  stage: report
  script:
    - ci-yaml-shell/report_executor.sh
  only:
    - master
    - develop
    - tags
  when: on_failure
  tags:
    - iOS

<!-- cleanup_runner:
  stage: cleanup
  script:
    - rm -fr ci-yaml-shell
  when: always -->
